import type { SearchOption } from './types';

export const METERS_OPTIONS = [
  { id: 1, name: 'أحذ الكامل' },
  { id: 2, name: 'مشطور الرجز' },
  { id: 3, name: 'مخلع البسيط' },
  { id: 4, name: 'موشح' },
  { id: 5, name: 'القوما' },
  { id: 6, name: 'الهزج' },
  { id: 7, name: 'مجزوء الرمل' },
  { id: 8, name: 'مجزوء موشح' },
  { id: 9, name: 'منهوك' },
  { id: 10, name: 'الكامل' },
  { id: 11, name: 'المجتث' },
  { id: 12, name: 'مجزوء الطويل' },
  { id: 13, name: 'مخلع' },
  { id: 14, name: 'الدوبيت' },
  { id: 15, name: 'الوافر' },
  { id: 16, name: 'المواليا' },
  { id: 18, name: 'المديد' },
  { id: 19, name: 'الطويل' },
  { id: 20, name: 'السلسلة' },
  { id: 21, name: 'مشطور' },
  { id: 22, name: 'المقتضب' },
  { id: 23, name: 'مجزوء الوافر' },
  { id: 24, name: 'أحذ' },
  { id: 26, name: 'المضارع' },
  { id: 27, name: 'مجزوء الخفيف' },
  { id: 29, name: 'السريع' },
  { id: 30, name: 'منهوك المنسرح' },
  { id: 31, name: 'المنسرح' },
  { id: 32, name: 'مربع' },
  { id: 33, name: 'مجزوء الرجز' },
  { id: 34, name: 'المتدارك' },
  { id: 35, name: 'عدد' },
  { id: 36, name: 'المتقارب' },
  { id: 37, name: 'الرجز' },
  { id: 38, name: 'مجزوء المتقارب' },
  { id: 39, name: 'الخفيف' },
  { id: 40, name: 'مجزوء الهزج' },
  { id: 41, name: 'الرمل' },
  { id: 42, name: 'مجزوء' },
  { id: 43, name: 'البسيط' },
  { id: 44, name: 'مجزوء الكامل' },
] as const satisfies readonly SearchOption[];
