import type { SearchOption } from './types';

export const RHYMES_OPTIONS = [
  { id: 1, name: 'الميم' },
  { id: 2, name: 'الهاء' },
  { id: 3, name: 'الظاء' },
  { id: 4, name: 'الواو' },
  { id: 6, name: 'الشين' },
  { id: 7, name: 'الزاى' },
  { id: 8, name: 'النون' },
  { id: 13, name: 'الدال' },
  { id: 14, name: 'الفاء' },
  { id: 15, name: 'الباء' },
  { id: 16, name: 'الخاء' },
  { id: 17, name: 'الياء' },
  { id: 18, name: 'الضاد' },
  { id: 19, name: 'التاء' },
  { id: 20, name: 'اللام' },
  { id: 24, name: 'الحاء' },
  { id: 26, name: 'السين' },
  { id: 30, name: 'الطاء' },
  { id: 31, name: 'الكاف' },
  { id: 34, name: 'الثاء' },
  { id: 35, name: 'الراء' },
  { id: 36, name: 'الألف' },
  { id: 38, name: 'الغين' },
  { id: 39, name: 'الذال' },
  { id: 41, name: 'الهمزة' },
  { id: 42, name: 'الجيم' },
  { id: 43, name: 'الصاد' },
  { id: 44, name: 'القاف' },
  { id: 45, name: 'العين' },
] as const satisfies readonly SearchOption[];
