import type { SearchOption } from './types';

export const THEMES_OPTIONS = [
  { id: 1, name: 'دينية' },
  { id: 2, name: 'عتاب' },
  { id: 3, name: 'عدل' },
  { id: 4, name: 'هجاء' },
  { id: 5, name: 'اعتذار' },
  { id: 6, name: 'رومنسية' },
  { id: 7, name: 'ذم' },
  { id: 9, name: 'من' },
  { id: 10, name: 'ابتهال' },
  { id: 11, name: 'شوق' },
  { id: 12, name: 'قصيرة' },
  { id: 13, name: 'فراق' },
  { id: 14, name: 'سياسية' },
  { id: 15, name: 'جود' },
  { id: 16, name: 'معلقة' },
  { id: 17, name: 'غزل' },
  { id: 18, name: 'مدح' },
  { id: 19, name: 'رثاء' },
  { id: 20, name: 'نصيحة' },
  { id: 21, name: 'حزينة' },
  { id: 22, name: 'رحمة' },
  { id: 23, name: 'حكمة' },
  { id: 24, name: 'عامة' },
  { id: 25, name: 'أنشودة' },
  { id: 26, name: 'صبر' },
  { id: 27, name: 'وطن' },
] as const satisfies readonly SearchOption[];
