export const POSTGRES_EDGE_CONFIG = {
  POOL_MAX: 1,
  IDLE_TIMEOUT_SECONDS: 20,
  CONNECT_TIMEOUT_SECONDS: 5,
  MAX_LIFETIME_SECONDS: 60,
  APPLICATION_NAME: 'qafiyah-edge',
} as const;

export const POSTGRES_LONG_LIVED_CONFIG = {
  POOL_MAX: 20,
  IDLE_TIMEOUT_SECONDS: 300,
  CONNECT_TIMEOUT_SECONDS: 30,
  MAX_LIFETIME_SECONDS: 1800,
  APPLICATION_NAME: 'qafiyah-long-lived',
} as const;
