#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

echo "Formatting code..."
pnpm run format

echo "Linting and fixing..."
pnpm run lint:fix

echo "Checking types..."
pnpm run check-types

echo "Pre-commit checks passed!"
